country_name: "bulgaria"
ssp_input_file_name: "BGR_real_data_20250625.csv"
ssp_transformation_cw: "ssp_bulgaria_transformation_v0.xlsx"
set_lndu_reallocation_factor_to_zero: true
energy_model_flag: true