country_name: "bulgaria"
ssp_input_file_name: "sisepuede_raw_inputs_latest_BGR_oct_29.csv"
ssp_transformation_cw: "ssp_bulgaria_transformation_cw_test_neg_emissions.xlsx"
set_lndu_reallocation_factor_to_zero: true
energy_model_flag: true